In [ ]:
#CHALLENGE:

[0.54670313 0.53260812 0.12164592 0.86736192 0.58592254 0.26333473
 0.20134039 0.63997188 0.44165999 0.3229993  0.41488953 0.66932199
 0.81488626 0.27069557]
[0.73509803 0.8496084  0.72473754 0.54244827 0.38570052 0.24531299
 0.16069517 0.23139293 0.20085126]
[0.04148163 0.83418127 0.41470991]
[0.32758804 0.97039927 0.49942758 0.58472336 0.10097863]

#CLUE:Quantity is also a language

In [59]:
#process of generate challenge:
import numpy as np

a = np.random.rand(14)
a

array([0.90177678, 0.53372591, 0.20282289, 0.77359869, 0.02820519,
       0.71353988, 0.08887237, 0.67105506, 0.45602793, 0.67576101,
       0.02777444, 0.91417028, 0.2717547 , 0.52852237])

In [60]:
a = np.random.rand(9)
a

array([0.06498421, 0.2355226 , 0.17657006, 0.19370144, 0.74116738,
       0.64272167, 0.31535175, 0.72682162, 0.69566619])

In [61]:
a = np.random.rand(3)
a

array([0.36290595, 0.65210627, 0.09897441])

In [62]:
a = np.random.rand(5)
a

array([0.25058376, 0.34692649, 0.96929486, 0.02156848, 0.33560981])

In [66]:
#solution part 1: Gets the number of elements in each array
import numpy as np
a1 = ([0.90177678, 0.53372591, 0.20282289, 0.77359869, 0.02820519,
       0.71353988, 0.08887237, 0.67105506, 0.45602793, 0.67576101,
       0.02777444, 0.91417028, 0.2717547 , 0.52852237])
a2 = ([0.06498421, 0.2355226 , 0.17657006, 0.19370144, 0.74116738,
       0.64272167, 0.31535175, 0.72682162, 0.69566619])
a3 = ([0.36290595, 0.65210627, 0.09897441])
a4 = ([0.25058376, 0.34692649, 0.96929486, 0.02156848, 0.33560981])
print(len(a1),len(a2),len(a3),len(a4))

14 9 3 5


In [79]:
#solution part 2 : convert the number to the letter!
array = [14,9,3,5]
for i in array:
    letter = chr(ord('`')+i)
    print (letter)


n
i
c
e


In [ ]:
#so,the answer is "nice"!